
/*#define WRITEBYTE(WORD,BYTESTARTBITPOS,VAL)\
WORD=((WORD&~(0xFF<<BYTESTARTBITPOS))|\
      ((VAL<<BYTESTARTBITPOS)))

#define SETBIT(WORD,BITPOS)WORD|=1<<BITPOS
#define READWRITEBIT(DWORD,DBIT,SWORD,SBIT)\
        DWORD=((DWORD&~(1<<DBIT))|((SWORD>>SBIT)&1<<DBIT))

#define READBIT(WORD,BITPOS)((WORD>>BITPOS)&1)
#define WRITEBIT(WORD,BITPOS,BITLEVEL)\
        WORD=((WORD&~(1<<BITPOS))|(BITLEVEL<<BITPOS))

//#define WRITEBIT(WORD,BITPOS,BITLEVEL)\
  //      BITLEVEL?((WORD|=1<<BITPOS):(WORD&=~(1<<BITPOS)))
		
#define WRITE2PORTBIT(PORTNO,BITPOS,BITLEVEL)\
        ((PORTNO==0)?\
		 (BITLEVEL?(IOSET0=1<<BITPOS):(IOCLR0=1<<BITPOS)):\
		 (BITLEVEL ?(IOSET1=1<<BITPOS):(IOCLR1=1<<BITPOS)))		 

#define WRITENIBBLE(WORD,STARTBITPOS,VAL)\
        WORD=((WORD&~(15<<STARTBITPOS))|(VAL<<STARTBITPOS))		 

#define READNIBBLE(WORD,STARTBITPOS)\
		((WORD>>STARTBITPOS)&15) 		     
  */

              /*defines.h */

#define SETBIT(WORD,BITPOS) \
        (WORD|=(1<<BITPOS))
#define CLRBIT(WORD,BITPOS) \
        (WORD&=~(1<<BITPOS))
#define CPLBIT(WORD,BITPOS) \
        (WORD^=(1<<BITPOS))
#define WRITEBIT(WORD,BITPOS,BIT) \
        WORD=((WORD&~(1<<BITPOS))| \
				      (BIT<<BITPOS))
                  
#define READBIT(WORD,BITPOS) \
        ((WORD>>BITPOS)&1)

#define WRITENIBBLE(WORD,STARTBITPOS,NIBBLE) \
      WORD=((WORD&~(15<<STARTBITPOS))| \
           (NIBBLE<<STARTBITPOS))

#define READNIBBLE(WORD,STARTBITPOS) \
        ((WORD>>STARTBITPOS)&15)

#define WRITEBYTE(WORD,STARTBITPOS,BYTE) \
        WORD=((WORD&~(255<<STARTBITPOS))|\
             (BYTE<<STARTBITPOS))

#define READBYTE(WORD,STARTBITPOS) \
        ((WORD>>STARTBITPOS)&255)

#define WRITEHWORD(WORD,STARTBITPOS,HWORD) \
        WORD=((WORD&~(0xFFFF<<STARTBITPOS)) | \
				      (HWORD<<STARTBITPOS))
				
#define READWRITEBIT2(DWORD,WBIT,SWORD,RBIT) \
        DWORD=((DWORD&~(1<<WBIT))| \
				(((SWORD>>RBIT)&1)<<WBIT))
				
#define READWRITEBIT(WORD,WBIT,RBIT) \
        WORD=((WORD&~(1<<WBIT))| \
				(((WORD>>RBIT)&1)<<WBIT))

#define SSETBIT(WORD,BITPOS) WORD=1<<BITPOS
#define SCLRBIT SSETBIT    
